_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 5
                - 50
                - 53
                - 55
            "2":
                - 1
                - 5
                - 50
                - 53
                - 55
            "3":
                - 13
                - 15
                - 16
                - 23
                - 55
            "4": 3.12.7
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": darwin-arm64
data_path:
    value: src/data/data_storage/composite_signals_20250518T172140.npz
enabled:
    value: true
entity:
    value: kjm-vanderhorst-maastricht-university
exp_name:
    value: 00_baseline
group:
    value: null
include_frequency_bands:
    value: false
log_artifacts:
    value: true
model_type:
    value: multi_scale
models:
    value:
        - base:
            - kernel_sizes: 15
        - multi_scale:
            - kernel_sizes:
                - 5
                - 15
                - 30
n_components:
    value: 3
notes:
    value: ""
params:
    value:
        batch_size: 100
        epochs: 20
        learning_rate: 0.001
        loss_list:
            - reconstruction
            - frequency_reconstruction
            - energy_ordering
            - spectral_entropy
            - laplacian
            - ssft_coherence
        loss_weights:
            band_leakage: 1
            band_overlap: 1
            energy_ordering: 1
            frequency_reconstruction: 1
            laplacian: 0.005
            reconstruction: 2.5
            spectral_entropy: 0.005
            ssft_coherence: 2
            true_loss: 1
            wavelet_coherence: 1
        model_save_path: models/testing_batches.pth
        num_workers: 4
        predictions_save_path: src/data/testing_batches
project:
    value: thesis-signal-decomposition
random_state:
    value: 42
run:
    value:
        comment: ""
        exp_num: "00"
        experiment_name: 00_baseline
        name: baseline
        save_checkpoint: true
seed:
    value: 42
tags:
    value:
        - hydra
        - experiment
test_size:
    value: 0.2
