_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 5
                - 50
                - 53
                - 55
            "2":
                - 1
                - 5
                - 50
                - 53
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.7
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": darwin-arm64
band_leakage:
    value: 0.008371810813218517
batch_size:
    value: 8
epochs:
    value: 40
learning_rate:
    value: 0.0027858127329870295
model_save_path:
    value: models/sweep_model.pth
reconstruction:
    value: 1.27080816756645
wavelet_coherence:
    value: 1.7683455162077957
