defaults:
  - _self_  # Include the current file
  - training
  - model
  - dataset
  - wandb

run:
  exp_num: "00"
  name: "baseline"
  comment: ""
  experiment_name: ${run.exp_num}_${run.name}
  save_checkpoint: true


hydra:
  job_logging:
    disable_existing_loggers: true
  run:
    dir: .
  output_subdir: null

seed: 42