params:
  batch_size: 5 #Currently only 1 to debug my band leakage loss
  epochs: 20
  learning_rate: 1e-3
  loss_list:
    - band_leakage
  model_save_path: models/band_leakage_test.pth
  n_components: 2  # Number of components for RRCNNDecomposer
  loss_weights:
    wavelet_coherence: 1.0
    reconstruction: 1.0
    band_leakage: 0.00000001
    true_loss: 1.0
    band_overlap: 0.000001
    ssft_coherence: 1