params:
  batch_size: 5
  epochs: 20
  learning_rate: 1e-3
  loss_list:
    - wavelet_coherence
    - mse
  model_save_path: "/Users/kaspervanderhorst/Desktop/thesis/models/rrcnn_decomposer_mock_test_with_bands.pth"
  n_components: 2  # Number of components for RRCNNDecomposer