params:
  batch_size: 10
  epochs: 20
  learning_rate: 1e-3
  loss_list:
    - reconstruction
    - frequency_reconstruction
    - band_leakage
  model_save_path: models/nonstationary_reconstruction_fr.pth
  predictions_save_path: src/data/data_storage/nonstationary_reconstruction_fr_predictions
  loss_weights:
    wavelet_coherence: 1.0
    reconstruction: 1.0
    band_leakage: 1e-1
    true_loss: 1.0
    band_overlap: 0.000001
    ssft_coherence: 1
    frequency_reconstruction: 100