params:
  batch_size: 10
  epochs: 20
  learning_rate: 1e-3
  loss_list:
    - reconstruction
    - frequency_reconstruction
    - energy_ordering
    - spectral_entropy
    - laplacian
    - ssft_coherence
  model_save_path: models/nonstationary_model_3_signals.pth
  predictions_save_path: src/data/data_storage/nonstationary_model_3_signals
  loss_weights:
    wavelet_coherence: 1.0
    reconstruction: 2.5
    band_leakage: 1.0
    true_loss: 1.0
    band_overlap: 1.0
    ssft_coherence: 2.0
    frequency_reconstruction: 1.0
    energy_ordering: 1.0
    spectral_entropy: 0.005
    laplacian: 0.005