params:
  batch_size: 5
  epochs: 20
  learning_rate: 1e-3
  loss_list:
    - band_leakage
    - reconstruction
  model_save_path: models/band_reconstruction_wavelet.pth
  n_components: 2  # Number of components for RRCNNDecomposer
  loss_weights:
    wavelet_coherence: 1.0
    reconstruction: 1.0
    band_leakage: 0.0000001
    true_loss: 1.0
    band_overlap: 0.0000005